# 配置数据源
spring:
  datasource:
    url: jdbc:mysql:///dbactivity?serverTimezone=UTC
    username: root
    password: root

  # 配置spring web
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
    suffix: .html
  # 配置热部署插件
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: /templates/pages/*
# 配置关闭log
  main:
    banner-mode: off

# 配置日志
logging:
  level:
   com.nicai.hiactivity: debug


# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: '*'


